document.addEventListener('DOMContentLoaded', () => {
    const translations = {
        en: {
            mealTitle: 'What should I eat for breakfast, lunch, and dinner?',
            mealSubtitle: 'We recommend open, highly rated places near you by time of day.',
            locationBtn: 'Get recommendations near me',
            locationHelper: 'Allow location access to see open, top-rated places with photos.',
            timeLabel: 'It is lunch time now',
            timeIntro: 'See breakfast, lunch, and dinner picks with photos.',
            breakfastTitle: 'What should I eat for breakfast',
            lunchTitle: 'What should I eat for lunch',
            dinnerTitle: 'What should I eat for dinner',
            menuNote: 'For menu details, open the restaurant link.',
            recommendTitle: 'Recommendations for now',
            recommendSubtitle: 'Tap the button to get time-based recommendations.',
            openListTitle: 'Open restaurants near you',
            openListSubtitle: 'Curated from nearby places with strong reviews.',
            reviewNote: 'Taste/cleanliness/menu summaries are inferred from review keywords.',
            dessertTitle: 'How about dessert after a meal?',
            dessertSubtitle: 'Highly rated cafes with photos.',
            dessertNote: 'Images are provided by Google and may show menus or the venue.',
            menuTitle: 'What should I eat today?',
            menuSubtitle: 'Get a quick menu suggestion in seconds.',
            animalTestLink: 'Animal Face Test',
            contactLink: 'Contact Us',
            contactTitle: 'Contact Us',
            contactIntroTitle: 'How to reach us',
            contactIntroText: 'Use this form for feedback, policy questions, or data issues.',
            contactResponseTitle: 'Response time',
            contactResponseText: 'We typically reply within 2–3 business days.',
            contactNote: 'For urgent issues, include a clear subject and screenshots.',
            formName: 'Name:',
            formEmail: 'Email:',
            formMessage: 'Message:',
            formSubmit: 'Send Message',
            backLink: 'Back to Menu Picker',
            themeToggle: 'Toggle Theme',
            pickButton: 'Pick for me',
            againButton: 'Pick another',
            categoryLabel: 'Pick a category',
            categoryAll: 'All',
            categoryKorean: 'Korean',
            categoryJapanese: 'Japanese',
            categoryChinese: 'Chinese',
            categoryWestern: 'Western',
            categoryFast: 'Quick & Easy',
            resultPlaceholder: 'Your menu suggestion appears here.',
            menuSectionTitle: 'When you need a fast menu pick',
            menuSectionIntro: 'Choosing what to eat can be the hardest part of a busy day. This site helps you decide quickly with a short selection flow.',
            menuTipsTitle: 'Tips for better picks',
            menuTip1: 'Narrow the category to get more satisfying results.',
            menuTip2: 'Decide your budget or dining situation first.',
            menuTip3: 'Rotate categories to avoid repeating the same foods.',
            menuGuideTitle: 'Usage guide',
            menuGuideText: 'Recommendations are for reference only. Consider allergies and health conditions before deciding.',
            menuIdeasTitle: 'Today’s menu ideas',
            menuIdea1: 'Hearty meal: Kimchi stew + rolled omelet',
            menuIdea2: 'Light lunch: Salad bowl + chicken breast',
            menuIdea3: 'Mood boost: Ramen + mini fritters',
            menuIdea4: 'Home-style: Bulgogi + fresh greens',
            overviewTitle: 'What this site does',
            overviewBody1: 'This site helps you decide what to eat and find open places nearby. It includes a quick quiz and a light animal face test.',
            overviewBody2: 'Recommendations come from public place data with clear filters. We focus on fast, honest choices over hype.',
            overviewCard1Title: 'Location-based picks',
            overviewCard1Text: 'With your permission, we show open restaurants and cafes near you.',
            overviewCard2Title: 'Time-aware suggestions',
            overviewCard2Text: 'Breakfast, lunch, and dinner use different keywords to fit the moment.',
            overviewCard3Title: 'Lightweight fun',
            overviewCard3Text: 'The quiz and animal face test are for entertainment only.',
            howTitle: 'How recommendations are selected',
            howIntro: 'We apply simple filters to keep results consistent and easy to understand.',
            howStep1: 'Use Google Places data for nearby businesses within about 2.5 km.',
            howStep2: 'Filter to places marked open now and meeting minimum rating thresholds.',
            howStep3: 'Show a short list so you can compare quickly.',
            howStep4: 'If details are missing, we show a minimal card or an empty-state message.',
            dataTitle: 'Data sources & limitations',
            dataItem1: 'Ratings, review counts, hours, and photos come from Google Places.',
            dataItem2: 'Results depend on public listing accuracy and can change.',
            dataItem3: 'We do not guarantee pricing, menus, or seat availability.',
            dataItem4: 'Check the official page or call ahead before visiting.',
            qualityTitle: 'Quality and transparency',
            qualityBody1: 'We avoid excessive ads and show ads only on content-rich screens.',
            qualityList1: 'Clear explanations of how results are picked.',
            qualityList2: 'Location is optional and used only with consent.',
            qualityList3: 'Regular updates to improve clarity and reliability.',
            faqTitle: 'FAQ',
            faqQ1: 'Do you store my location?',
            faqA1: 'No. Location is used only in the browser to request nearby results from Google Places.',
            faqQ2: 'Are the review summaries automated?',
            faqA2: 'Yes. They are lightweight keyword estimates and can be inaccurate.',
            faqQ3: 'Why do I see fewer results?',
            faqA3: 'Filters for open now and rating may remove many places nearby.',
            faqQ4: 'Can I use this without location?',
            faqA4: 'You can use the quiz and test, but location is required for nearby places.',
            quizTitle: 'Today’s nonsense quiz',
            quizSubtitle: 'We show a random question by country (language).',
            quizButton: 'Show another quiz',
            quizShowAnswer: 'Show answer',
            quizHideAnswer: 'Hide answer',
            animalTestTitle: 'Animal Face Test',
            animalTestSubtitle: 'Find out which animal vibe you give off today.',
            cameraPlaceholder: 'Camera preview will appear here.',
            startCamera: 'Start Camera',
            stopCamera: 'Stop Camera',
            uploadLabel: 'Or upload a photo',
            chooseFile: 'Choose a file',
            noFileSelected: 'No file selected',
            resultTitle: 'Result',
            backToMenu: 'BACK',
            animalInfoTitle: 'About the animal face test',
            animalInfoIntro: 'This test predicts a dog/cat vibe from a photo. It is for fun and reference only, not identification.',
            animalPrivacyTitle: 'Privacy & image handling',
            animalPrivacy1: 'Image analysis runs in the browser after loading the model.',
            animalPrivacy2: 'Uploaded photos are not stored on a server and reset on refresh.',
            animalPrivacy3: 'Camera access works only when you allow it.',
            animalAccuracyTitle: 'Accuracy & limits',
            animalAccuracyText: 'Results can vary by lighting, angle, and image quality. Try multiple shots.',
            animalFaqTitle: 'FAQ',
            animalFaq1: 'Q. Are photos stored? A. No, they are processed locally.',
            animalFaq2: 'Q. What happens if I stop the camera? A. Predictions stop immediately.',
            animalFaq3: 'Q. The result looks odd. A. Try different lighting or angles.',
            footerAbout: 'About',
            footerPrivacy: 'Privacy Policy',
            footerTerms: 'Terms of Use',
            aboutTitle: 'About',
            aboutSubtitle: 'A small set of lifestyle tools for faster choices and a bit of fun.',
            aboutSectionOneTitle: 'What do we provide?',
            aboutSectionOneText: 'We offer light decision helpers like menu picks and animal face tests to reduce daily decision time.',
            aboutSectionTwoTitle: 'Operating principles',
            aboutPolicy1: 'We prioritize user experience and avoid excessive ads.',
            aboutPolicy2: 'We collect minimal personal data and keep policies transparent.',
            aboutPolicy3: 'We update content regularly to improve quality.',
            aboutSectionThreeTitle: 'Data sources & responsibility',
            aboutSectionThreeText: 'Nearby suggestions use public Google Places data, which may change. Please verify details before visiting.',
            aboutSectionFourTitle: 'Updates & feedback',
            aboutSectionFourText: 'We review feedback and update copy and features regularly.',
            backHome: 'Back to Home',
            privacyTitle: 'Privacy Policy',
            privacySubtitle: 'We handle minimal data and communicate clearly.',
            privacyCollectTitle: 'Information we collect',
            privacyCollect1: 'Name, email, and message submitted via the contact form',
            privacyCollect2: 'Anonymous visit analytics for service improvement',
            privacyCollect3: 'Device location for location-based recommendations (with user consent)',
            privacyImageTitle: 'Animal test image handling',
            privacyImage1: 'Camera/upload images are processed in the browser and not stored.',
            privacyImage2: 'Camera access runs only with user permission.',
            privacyAdsTitle: 'Ads & cookies',
            privacyAdsText: 'Third-party ad partners like Google AdSense may use cookies. You can manage cookies in your browser.',
            privacyContactTitle: 'Contact',
            privacyContactText: 'For privacy inquiries, please use the Contact Us page.',
            termsTitle: 'Terms of Use',
            termsSubtitle: 'By using this site, you agree to the terms below.',
            termsServiceTitle: 'Service scope',
            termsServiceText: 'The site provides information and entertainment features without guaranteeing results.',
            termsLiabilityTitle: 'Limitation of liability',
            termsLiabilityText: 'Users are responsible for decisions made based on the service.',
            termsIpTitle: 'Intellectual property',
            termsIpText: 'Content and design belong to the operator. Unauthorized copying is prohibited.',
            termsChangeTitle: 'Changes to terms',
            termsChangeText: 'We may update these terms and will post changes on the site.'
        },
        ko: {
            mealTitle: '오늘 아침·점심·저녁 뭐먹지?',
            mealSubtitle: '위치 기반으로 평이 좋은 음식점을 시간대별로 추천해드려요.',
            locationBtn: '내 위치로 추천받기',
            locationHelper: '위치 사용에 동의하면 현재 영업 중인 맛집과 사진을 보여드려요.',
            timeLabel: '지금은 점심 추천 시간이에요',
            timeIntro: '아침/점심/저녁 각각에 맞는 음식점과 메뉴를 사진과 함께 보여드립니다.',
            breakfastTitle: '오늘 아침 뭐먹지',
            lunchTitle: '오늘 점심 뭐먹지',
            dinnerTitle: '오늘 저녁 뭐먹지',
            menuNote: '메뉴 상세는 각 음식점 링크에서 확인할 수 있어요.',
            recommendTitle: '지금 시간대 추천',
            recommendSubtitle: '추천받기 버튼을 누르면 현재 시간대에 맞는 음식점을 보여드립니다.',
            openListTitle: '현재 영업 중인 음식점',
            openListSubtitle: '가까운 곳에서 평점과 리뷰 기반으로 선별한 목록입니다.',
            reviewNote: '맛/청결/추천 메뉴 요약은 리뷰 키워드를 기반으로 추정됩니다.',
            dessertTitle: '식사 후에는 이런 디저트 어때요?',
            dessertSubtitle: '평점이 높은 카페와 사진을 골라 보여드립니다.',
            dessertNote: '사진은 Google 제공 이미지이며 매장/메뉴 사진일 수 있습니다.',
            menuTitle: '오늘 메뉴 뭐먹지',
            menuSubtitle: '몇 초 만에 오늘의 메뉴를 추천받아 보세요.',
            animalTestLink: '동물상 테스트',
            contactLink: '문의하기',
            contactTitle: '문의하기',
            contactIntroTitle: '문의 안내',
            contactIntroText: '피드백, 정책 문의, 데이터 오류 제보에 이 양식을 사용해 주세요.',
            contactResponseTitle: '답변 일정',
            contactResponseText: '보통 2~3영업일 내 회신합니다.',
            contactNote: '긴급한 이슈는 제목과 스크린샷을 함께 보내 주세요.',
            formName: '이름:',
            formEmail: '이메일:',
            formMessage: '메시지:',
            formSubmit: '메시지 보내기',
            backLink: '메뉴 추천으로 돌아가기',
            themeToggle: '테마 변경',
            pickButton: '추천받기',
            againButton: '다시 추천',
            categoryLabel: '카테고리를 선택하세요',
            categoryAll: '전체',
            categoryKorean: '한식',
            categoryJapanese: '일식',
            categoryChinese: '중식',
            categoryWestern: '양식',
            categoryFast: '간편식',
            resultPlaceholder: '오늘 메뉴 추천 결과가 여기 표시돼요.',
            menuSectionTitle: '오늘 메뉴 추천이 필요한 순간',
            menuSectionIntro: '바쁜 하루에 메뉴를 고르는 시간이 가장 어렵다는 피드백이 많습니다. 이 사이트는 짧은 선택 과정만으로도 오늘의 메뉴를 빠르게 결정할 수 있도록 돕기 위해 만들었습니다.',
            menuTipsTitle: '추천이 더 유용해지는 팁',
            menuTip1: '카테고리를 좁히면 더 만족스러운 선택이 나옵니다.',
            menuTip2: '한 끼 예산이나 식사 상황(혼밥, 모임 등)을 먼저 정해 보세요.',
            menuTip3: '과도한 편중을 피하려면 다양한 카테고리를 번갈아 선택해 보세요.',
            menuGuideTitle: '이용 안내',
            menuGuideText: '추천 결과는 참고용이며, 알레르기나 건강 상태에 맞는 식단은 개인 판단이 필요합니다. 사용자의 선택을 돕기 위한 정보 제공 목적입니다.',
            menuIdeasTitle: '오늘 메뉴 아이디어',
            menuIdea1: '든든한 한 끼: 김치찌개 + 계란말이',
            menuIdea2: '가벼운 점심: 샐러드볼 + 닭가슴살',
            menuIdea3: '기분 전환: 라멘 + 미니 튀김',
            menuIdea4: '집밥 느낌: 불고기 + 쌈채소',
            overviewTitle: '이 사이트가 하는 일',
            overviewBody1: '이 사이트는 오늘 먹을 메뉴를 빠르게 결정하고, 현재 영업 중인 주변 맛집을 찾는 데 도움을 줍니다. 간단한 퀴즈와 동물상 테스트도 함께 제공합니다.',
            overviewBody2: '추천은 공개된 장소 데이터를 바탕으로 몇 가지 기준을 투명하게 적용해 제공합니다. 과장 없이 빠른 선택을 돕는 것이 목표입니다.',
            overviewCard1Title: '위치 기반 추천',
            overviewCard1Text: '허용 시 주변의 영업 중인 음식점과 카페를 보여줍니다.',
            overviewCard2Title: '시간대 맞춤',
            overviewCard2Text: '아침/점심/저녁에 맞는 키워드로 추천을 달리합니다.',
            overviewCard3Title: '가벼운 재미',
            overviewCard3Text: '퀴즈와 동물상 테스트는 재미와 참고용입니다.',
            howTitle: '추천 방식',
            howIntro: '아래 기준을 적용해 간단하고 일관된 결과를 제공합니다.',
            howStep1: '약 2.5km 이내의 Google Places 데이터를 조회합니다.',
            howStep2: '영업 중 표시가 있는 곳과 최소 평점 기준을 통과한 곳만 보여줍니다.',
            howStep3: '선택 부담을 줄이기 위해 목록을 작게 유지합니다.',
            howStep4: '정보가 부족하면 요약 카드 또는 안내 메시지를 표시합니다.',
            dataTitle: '데이터 출처 및 한계',
            dataItem1: '평점, 리뷰 수, 영업시간, 사진은 Google Places에서 제공됩니다.',
            dataItem2: '공개 정보의 정확도에 따라 결과가 달라질 수 있습니다.',
            dataItem3: '가격, 메뉴, 좌석 가능 여부는 보장하지 않습니다.',
            dataItem4: '방문 전 공식 페이지 확인 또는 연락을 권장합니다.',
            qualityTitle: '품질과 투명성',
            qualityBody1: '과도한 광고를 피하고, 콘텐츠가 있는 화면에서만 광고가 노출되도록 설계합니다.',
            qualityList1: '추천 기준을 명확하게 공개합니다.',
            qualityList2: '위치는 선택 사항이며 동의 시에만 사용됩니다.',
            qualityList3: '신뢰를 위해 문구와 기능을 꾸준히 개선합니다.',
            faqTitle: '자주 묻는 질문',
            faqQ1: '위치 정보가 저장되나요?',
            faqA1: '아니요. 위치는 브라우저에서만 사용되며, Google Places에 근처 결과를 요청하는 데 쓰입니다.',
            faqQ2: '리뷰 요약은 어떻게 만들어지나요?',
            faqA2: '리뷰 키워드를 기반으로 한 간단한 추정이며 정확하지 않을 수 있습니다.',
            faqQ3: '추천이 적게 나오는 이유는?',
            faqA3: '영업 중 여부와 평점 기준을 통과한 곳만 보여주기 때문입니다.',
            faqQ4: '위치 허용 없이도 쓸 수 있나요?',
            faqA4: '퀴즈와 테스트는 이용 가능하지만, 주변 추천에는 위치 허용이 필요합니다.',
            quizTitle: '오늘의 넌센스 퀴즈',
            quizSubtitle: '국가(언어)별로 다른 문제를 랜덤으로 보여드립니다.',
            quizButton: '다른 퀴즈 보기',
            quizShowAnswer: '정답 보기',
            quizHideAnswer: '정답 숨기기',
            animalTestTitle: '동물상 테스트',
            animalTestSubtitle: '오늘의 동물상 분위기를 확인해보세요.',
            cameraPlaceholder: '카메라 화면이 여기에 표시돼요.',
            startCamera: '카메라 시작',
            stopCamera: '카메라 종료',
            uploadLabel: '또는 사진 업로드',
            chooseFile: '파일 선택',
            noFileSelected: '선택된 파일 없음',
            resultTitle: '결과',
            backToMenu: 'BACK',
            animalInfoTitle: '동물상 테스트 안내',
            animalInfoIntro: '이 테스트는 사용자가 제공한 사진을 기반으로 강아지상/고양이상 분위기를 예측합니다. 재미와 참고를 위한 결과이며, 과학적 진단이나 신원 판별 목적이 아닙니다.',
            animalPrivacyTitle: '개인정보와 이미지 처리',
            animalPrivacy1: '이미지 분석은 브라우저에서 모델을 불러와 수행합니다.',
            animalPrivacy2: '업로드한 사진은 서버로 저장되지 않으며, 페이지 새로고침 시 초기화됩니다.',
            animalPrivacy3: '카메라는 사용자가 허용한 경우에만 접근합니다.',
            animalAccuracyTitle: '정확도와 한계',
            animalAccuracyText: '조명, 각도, 화질에 따라 결과가 달라질 수 있습니다. 여러 장을 시도해 보세요.',
            animalFaqTitle: '자주 묻는 질문',
            animalFaq1: 'Q. 사진이 저장되나요? A. 아니요, 브라우저에서만 처리됩니다.',
            animalFaq2: 'Q. 카메라를 끄면 어떻게 되나요? A. 즉시 예측이 중단됩니다.',
            animalFaq3: 'Q. 결과가 이상해요. A. 조명과 얼굴 각도를 바꿔 다시 시도해 보세요.',
            footerAbout: '사이트 소개',
            footerPrivacy: '개인정보 처리방침',
            footerTerms: '이용약관',
            aboutTitle: '사이트 소개',
            aboutSubtitle: '빠른 선택과 재미있는 경험을 제공하는 간단한 라이프스타일 도구 모음입니다.',
            aboutSectionOneTitle: '무엇을 제공하나요?',
            aboutSectionOneText: '오늘 메뉴 추천과 동물상 테스트 같은 가벼운 선택 도구를 제공해 일상의 고민 시간을 줄이는 것이 목표입니다.',
            aboutSectionTwoTitle: '운영 원칙',
            aboutPolicy1: '사용자 경험을 우선하며, 과도한 광고 배치를 지양합니다.',
            aboutPolicy2: '개인정보를 최소 수집하고, 투명한 정책을 유지합니다.',
            aboutPolicy3: '콘텐츠 품질을 높이기 위해 정기적으로 업데이트합니다.',
            aboutSectionThreeTitle: '데이터와 책임',
            aboutSectionThreeText: '주변 추천은 Google Places 공개 정보를 사용하며, 정확성은 제공처에 따라 달라질 수 있습니다. 방문 전 확인을 권장합니다.',
            aboutSectionFourTitle: '업데이트와 피드백',
            aboutSectionFourText: '사용자 의견을 반영해 질문, 문구, 기능을 정기적으로 개선합니다.',
            backHome: '홈으로',
            privacyTitle: '개인정보 처리방침',
            privacySubtitle: '본 사이트는 최소한의 개인정보만 처리하며, 투명한 고지를 우선합니다.',
            privacyCollectTitle: '수집하는 정보',
            privacyCollect1: '문의하기 폼에서 사용자가 입력한 이름, 이메일, 메시지',
            privacyCollect2: '서비스 품질 개선을 위한 익명 방문 통계(브라우저 쿠키 또는 로그)',
            privacyCollect3: '위치 기반 추천 제공을 위한 기기 위치 정보(사용자 동의 시)',
            privacyImageTitle: '동물상 테스트 이미지 처리',
            privacyImage1: '카메라/업로드 이미지는 브라우저에서만 처리되며 서버에 저장되지 않습니다.',
            privacyImage2: '사용자가 카메라 접근을 허용한 경우에만 작동합니다.',
            privacyAdsTitle: '광고 및 쿠키',
            privacyAdsText: 'Google AdSense 등 서드파티 광고 파트너가 쿠키를 사용할 수 있습니다. 사용자는 브라우저 설정에서 쿠키를 관리할 수 있습니다.',
            privacyContactTitle: '문의',
            privacyContactText: '개인정보 관련 문의는 Contact Us 페이지를 이용해 주세요.',
            termsTitle: '이용약관',
            termsSubtitle: '본 사이트를 이용하면 아래 약관에 동의한 것으로 간주합니다.',
            termsServiceTitle: '서비스 제공',
            termsServiceText: '사이트는 정보 제공과 मनोर 목적의 서비스를 제공하며, 결과의 정확성을 보장하지 않습니다.',
            termsLiabilityTitle: '책임의 한계',
            termsLiabilityText: '사용자는 서비스 이용으로 인한 결과를 본인의 책임 하에 판단해야 합니다.',
            termsIpTitle: '지식재산권',
            termsIpText: '사이트의 콘텐츠와 디자인은 운영자에게 권리가 있으며, 무단 복제 및 배포를 금합니다.',
            termsChangeTitle: '약관 변경',
            termsChangeText: '운영자는 필요 시 약관을 변경할 수 있으며, 변경 사항은 사이트에 게시합니다.'
        },
        ja: {
            mealTitle: '朝・昼・夜、何を食べる？',
            mealSubtitle: '時間帯ごとに近くの人気店をおすすめします。',
            locationBtn: '近くのおすすめを見る',
            locationHelper: '位置情報を許可すると営業中のおすすめを表示します。',
            timeLabel: '今は昼ごはんの時間です',
            timeIntro: '朝・昼・夜それぞれのおすすめを写真付きで表示します。',
            breakfastTitle: '今日の朝ごはんは？',
            lunchTitle: '今日の昼ごはんは？',
            dinnerTitle: '今日の夜ごはんは？',
            menuNote: 'メニューの詳細は各店舗リンクで確認できます。',
            recommendTitle: '現在のおすすめ',
            recommendSubtitle: 'ボタンを押すと時間帯に合わせて表示します。',
            openListTitle: '営業中の飲食店',
            openListSubtitle: '近くで評価の高いお店をまとめています。',
            reviewNote: '味/清潔さ/人気メニューはレビューのキーワードから推定します。',
            dessertTitle: '食後のデザートはいかが？',
            dessertSubtitle: '高評価のカフェと写真を紹介します。',
            dessertNote: '画像はGoogle提供で、店内やメニュー写真の場合があります。',
            menuTitle: '今日のごはん、何にする？',
            menuSubtitle: 'すぐに今日のメニューをおすすめします。',
            animalTestLink: 'アニマル診断',
            contactLink: 'お問い合わせ',
            contactTitle: 'お問い合わせ',
            contactIntroTitle: 'お問い合わせについて',
            contactIntroText: 'フィードバック、ポリシー関連、データの誤り報告はこちらから。',
            contactResponseTitle: '返信目安',
            contactResponseText: '通常は2〜3営業日以内に返信します。',
            contactNote: '急ぎの場合は件名とスクリーンショットを添えてください。',
            formName: '名前:',
            formEmail: 'Eメール:',
            formMessage: 'メッセージ:',
            formSubmit: 'メッセージを送信',
            backLink: 'メニューおすすめに戻る',
            themeToggle: 'テーマの切り替え',
            pickButton: 'おすすめして',
            againButton: 'もう一回',
            categoryLabel: 'カテゴリを選んでください',
            categoryAll: 'すべて',
            categoryKorean: '韓国料理',
            categoryJapanese: '日本料理',
            categoryChinese: '中華',
            categoryWestern: '洋食',
            categoryFast: '手軽なメニュー',
            resultPlaceholder: '今日のおすすめがここに表示されます。',
            menuSectionTitle: 'すぐ決めたいときに',
            menuSectionIntro: '忙しい日ほどメニュー選びが悩みの種。短い選択で今日の食事を素早く決められます。',
            menuTipsTitle: 'おすすめのコツ',
            menuTip1: 'カテゴリを絞るほど満足度が上がります。',
            menuTip2: '予算やシーン（ひとり/みんな）を先に決めましょう。',
            menuTip3: '偏りを避けるためにカテゴリをローテーション。',
            menuGuideTitle: '利用案内',
            menuGuideText: '結果は参考情報です。アレルギーや体調に合わせて判断してください。',
            menuIdeasTitle: '今日のメニューアイデア',
            menuIdea1: 'しっかり: キムチチゲ + 卵焼き',
            menuIdea2: '軽め: サラダボウル + チキン',
            menuIdea3: '気分転換: ラーメン + ミニ揚げ物',
            menuIdea4: '家庭風: プルコギ + 葉野菜',
            overviewTitle: 'このサイトでできること',
            overviewBody1: '今日のメニュー選びを素早く決め、営業中の近くのお店を探すためのサイトです。軽いクイズや動物顔テストも用意しています。',
            overviewBody2: '公開されている場所データにいくつかの基準を適用して、分かりやすいおすすめを表示します。大げさな演出はせず、判断の助けになることを重視します。',
            overviewCard1Title: '位置情報ベース',
            overviewCard1Text: '許可すると近くで営業中の飲食店やカフェを表示します。',
            overviewCard2Title: '時間帯に合わせた提案',
            overviewCard2Text: '朝・昼・夜に合うキーワードで候補を変えます。',
            overviewCard3Title: 'ライトな楽しみ',
            overviewCard3Text: 'クイズと動物顔テストはエンタメ目的です。',
            howTitle: 'おすすめの仕組み',
            howIntro: 'シンプルな条件で分かりやすい結果に絞ります。',
            howStep1: '約2.5km圏内のGoogle Placesデータを参照します。',
            howStep2: '営業中の表示と最低評価を満たすお店のみを表示します。',
            howStep3: '比較しやすいように少数の候補に絞ります。',
            howStep4: '情報が不足する場合は簡易カードまたは案内文を表示します。',
            dataTitle: 'データソースと制限',
            dataItem1: '評価、レビュー数、営業時間、写真はGoogle Placesから提供されます。',
            dataItem2: '公開情報の正確性によって結果が変わる可能性があります。',
            dataItem3: '価格、メニュー、空席は保証しません。',
            dataItem4: '来店前に公式ページの確認をおすすめします。',
            qualityTitle: '品質と透明性',
            qualityBody1: '過度な広告を避け、十分なコンテンツがある画面にのみ広告が表示されるようにしています。',
            qualityList1: '選定基準を明確にします。',
            qualityList2: '位置情報は同意した場合のみ使用します。',
            qualityList3: '文言と機能を継続的に改善します。',
            faqTitle: 'FAQ',
            faqQ1: '位置情報は保存されますか？',
            faqA1: 'いいえ。位置情報はブラウザ内でのみ使用し、近くの結果をGoogle Placesにリクエストするために使います。',
            faqQ2: 'レビュー要約は自動ですか？',
            faqA2: 'はい。キーワードによる簡易推定のため正確でない場合があります。',
            faqQ3: 'おすすめが少ないのはなぜ？',
            faqA3: '営業中と評価基準で絞っているためです。',
            faqQ4: '位置情報なしでも使えますか？',
            faqA4: 'クイズとテストは利用できますが、近くのおすすめには位置情報が必要です。',
            quizTitle: '今日のナンセンスクイズ',
            quizSubtitle: '国（言語）ごとにランダムで表示します。',
            quizButton: '別のクイズを見る',
            quizShowAnswer: '答えを見る',
            quizHideAnswer: '答えを隠す',
            animalTestTitle: 'アニマル診断',
            animalTestSubtitle: '今日の雰囲気に近い動物をチェック。',
            cameraPlaceholder: 'カメラ映像がここに表示されます。',
            startCamera: 'カメラ開始',
            stopCamera: 'カメラ停止',
            uploadLabel: 'または写真をアップロード',
            chooseFile: 'ファイルを選択',
            noFileSelected: '選択されていません',
            resultTitle: '結果',
            backToMenu: 'BACK',
            animalInfoTitle: 'アニマル診断について',
            animalInfoIntro: '写真から犬/猫っぽさを予測します。娯楽・参考用で、識別目的ではありません。',
            animalPrivacyTitle: 'プライバシーと画像処理',
            animalPrivacy1: 'モデルを読み込み、ブラウザ内で解析します。',
            animalPrivacy2: 'アップロード画像は保存されず、更新でリセットされます。',
            animalPrivacy3: 'カメラは許可された場合のみ使用します。',
            animalAccuracyTitle: '精度と制限',
            animalAccuracyText: '照明・角度・画質で結果が変わります。複数回試してください。',
            animalFaqTitle: 'よくある質問',
            animalFaq1: 'Q. 写真は保存されますか？ A. いいえ、ローカル処理です。',
            animalFaq2: 'Q. カメラを止めると？ A. 予測が停止します。',
            animalFaq3: 'Q. 結果が変です。 A. 照明や角度を変えてみてください。',
            footerAbout: 'サイト紹介',
            footerPrivacy: 'プライバシーポリシー',
            footerTerms: '利用規約',
            aboutTitle: 'サイト紹介',
            aboutSubtitle: '素早い選択と楽しさを提供する小さなライフスタイルツールです。',
            aboutSectionOneTitle: '提供内容',
            aboutSectionOneText: '今日のメニュー選びやアニマル診断など、軽い意思決定ツールを提供します。',
            aboutSectionTwoTitle: '運営方針',
            aboutPolicy1: 'ユーザー体験を最優先し、過度な広告を避けます。',
            aboutPolicy2: '個人情報は最小限にし、透明性を保ちます。',
            aboutPolicy3: '品質向上のために定期的に更新します。',
            aboutSectionThreeTitle: 'データと責任',
            aboutSectionThreeText: '近くのおすすめはGoogle Placesの公開情報を使用し、正確性は提供元に依存します。来店前に確認してください。',
            aboutSectionFourTitle: '更新とフィードバック',
            aboutSectionFourText: 'フィードバックをもとに文言や機能を定期的に改善します。',
            backHome: 'ホームへ',
            privacyTitle: 'プライバシーポリシー',
            privacySubtitle: '最小限の情報を扱い、透明性を重視します。',
            privacyCollectTitle: '収集する情報',
            privacyCollect1: 'お問い合わせフォームの名前・メール・メッセージ',
            privacyCollect2: '改善のための匿名アクセス統計',
            privacyCollect3: '位置情報ベースのおすすめのための端末位置情報（同意時）',
            privacyImageTitle: 'アニマル診断の画像処理',
            privacyImage1: '画像はブラウザ内で処理され、保存されません。',
            privacyImage2: 'カメラは許可時のみ利用します。',
            privacyAdsTitle: '広告とCookie',
            privacyAdsText: 'Google AdSense など第三者広告が Cookie を使用する場合があります。',
            privacyContactTitle: 'お問い合わせ',
            privacyContactText: 'プライバシーに関する問い合わせは Contact Us をご利用ください。',
            termsTitle: '利用規約',
            termsSubtitle: '本サイトの利用により以下に同意したものとみなします。',
            termsServiceTitle: 'サービス内容',
            termsServiceText: '情報提供・娯楽目的で提供し、結果の正確性は保証しません。',
            termsLiabilityTitle: '責任の範囲',
            termsLiabilityText: '利用による判断は利用者の責任で行ってください。',
            termsIpTitle: '知的財産',
            termsIpText: 'コンテンツとデザインの権利は運営者に帰属します。',
            termsChangeTitle: '規約の変更',
            termsChangeText: '必要に応じて変更し、サイトに掲載します。'
        }
    };

    const languageSwitcher = document.getElementById('language-switcher');
    const languageToggle = languageSwitcher ? languageSwitcher.querySelector('.lang-toggle') : null;
    const languageMenu = languageSwitcher ? languageSwitcher.querySelector('.lang-menu') : null;
    const languageOptions = languageSwitcher
        ? Array.from(languageSwitcher.querySelectorAll('.lang-option'))
        : [];

    const closeLanguageMenu = () => {
        if (!languageSwitcher || !languageToggle) {
            return;
        }
        languageSwitcher.classList.remove('open');
        languageToggle.setAttribute('aria-expanded', 'false');
    };

    const setLanguage = (language) => {
        document.querySelectorAll('[data-lang]').forEach(element => {
            const key = element.getAttribute('data-lang');
            if (translations[language] && translations[language][key]) {
                element.textContent = translations[language][key];
            }
        });

        // Translate menu-picker component
        const menuPicker = document.querySelector('menu-picker');
        if (menuPicker && typeof menuPicker.setLanguage === 'function') {
            menuPicker.setLanguage(language);
        }

        const animalPageElements = document.querySelectorAll('[data-lang]');
        if (animalPageElements.length) {
            const event = new CustomEvent('language-change', { detail: { language } });
            document.dispatchEvent(event);
        }

        // Translate theme toggle button
        const themeToggle = document.getElementById('theme-toggle');
        if (themeToggle) {
            themeToggle.textContent = translations[language].themeToggle;
        }

        if (languageSwitcher && languageToggle) {
            languageOptions.forEach(option => {
                option.setAttribute(
                    'aria-selected',
                    option.dataset.value === language ? 'true' : 'false'
                );
            });

            const selectedOption = languageOptions.find(option => option.dataset.value === language);
            if (selectedOption) {
                const selectedFlag = selectedOption.querySelector('.lang-flag');
                const selectedCode = selectedOption.querySelector('.lang-code');
                const toggleFlag = languageToggle.querySelector('.lang-flag');
                const toggleCode = languageToggle.querySelector('.lang-code');

                if (selectedFlag && toggleFlag) {
                    toggleFlag.src = selectedFlag.src;
                    toggleFlag.alt = selectedFlag.alt;
                }
                if (selectedCode && toggleCode) {
                    toggleCode.textContent = selectedCode.textContent;
                }
                languageToggle.dataset.value = language;
            }
        }
    };

    if (languageSwitcher && languageToggle && languageMenu) {
        languageToggle.addEventListener('click', () => {
            const isOpen = languageSwitcher.classList.toggle('open');
            languageToggle.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        });

        languageOptions.forEach(option => {
            option.addEventListener('click', () => {
                const selectedLanguage = option.dataset.value;
                localStorage.setItem('language', selectedLanguage);
                setLanguage(selectedLanguage);
                closeLanguageMenu();
            });
        });

        document.addEventListener('click', (event) => {
            if (!languageSwitcher.contains(event.target)) {
                closeLanguageMenu();
            }
        });

        document.addEventListener('keydown', (event) => {
            if (event.key === 'Escape') {
                closeLanguageMenu();
            }
        });
    }

    // Set initial language
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
});
